name: Build and Publish (Tags)

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zcq98
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Calculate Docker Tag
        id: vars
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: make docker-build VERSION=${{ env.TAG_NAME }}

      - name: Push Docker Image
        run: make docker-push VERSION=${{ env.TAG_NAME }}
